// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl2QCp40V8U0LM17x42YaRC7tE2aowqaw',
    appId: '1:320761724189:web:a6e798dc34956ee92b75f4',
    messagingSenderId: '320761724189',
    projectId: 'zad-al-daia',
    authDomain: 'zad-al-daia.firebaseapp.com',
    databaseURL: 'https://zad-al-daia-default-rtdb.firebaseio.com',
    storageBucket: 'zad-al-daia.firebasestorage.app',
    measurementId: 'G-9Q1F2200H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeByWottMjYf7GfBx93LG6Z3qZH3IddXs',
    appId: '1:320761724189:android:d5de73f0b10f4e932b75f4',
    messagingSenderId: '320761724189',
    projectId: 'zad-al-daia',
    databaseURL: 'https://zad-al-daia-default-rtdb.firebaseio.com',
    storageBucket: 'zad-al-daia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHhnScs1NMs0E2CGwFQKDM2Ly1LLOUT-Q',
    appId: '1:320761724189:ios:bfacfc842e34c3382b75f4',
    messagingSenderId: '320761724189',
    projectId: 'zad-al-daia',
    databaseURL: 'https://zad-al-daia-default-rtdb.firebaseio.com',
    storageBucket: 'zad-al-daia.firebasestorage.app',
    iosBundleId: 'com.dev3mk.zadAldaia',
  );
}
